POSITIVE_EMOTICONS = [':)', ':-)', '=)', ':D']
NEGATIVE_EMOTICONS = [':(', ':-(', ';(', '=(']

TWITTER_CONSUMER_KEY = 'llFby3tYUHl1zyJNTScs3bLfC'
TWITTER_CONSUMER_SECRET = 'zR51xj0BXvYmeMmzRX9sIBasRSUhyR6ZwE0KA57f7oZ2yuEpHG'
TWITTER_ACCESS_TOKEN = '28572918-s5agTTGFDrunOOlL0ktXMSRjEyFsWpgClmoxNtqVB'
TWITTER_ACCESS_TOKEN_SECRET = 'han6SSral5nof3LK3zi5fR1GWzidHnO8gfcYnZSMlkdOx'